version: "3.7"

networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:
    spendmanagement_api:
      container_name: spendmanagement_api
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_api
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker
      ports:
        - "8070:80"
      networks:
        - spendmanagement